Rails.application.routes.draw do
  get 'comment/index'
  get 'comment/new'
  get 'comment/show'
  get 'comment/edit'
  get 'comment/update'
  get 'comment/create'
  get 'comment/destroy'
  get 'book/index'
  get 'book/new'
  get 'book/show'
  get 'book/edit'
  get 'book/update'
  get 'book/create'
  get 'book/destroy'
  get 'genre/index'
  get 'genre/new'
  get 'genre/show'
  get 'genre/edit'
  get 'genre/update'
  get 'genre/create'
  get 'genre/destroy'
  get 'users/index'
  get 'users/new'
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  get 'users/create'
  get 'users/destroy'
  root to: 'pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end
