Rails.application.routes.draw do
  get 'comments/index'
  get 'comments/new'
  get 'comments/show'
  get 'comments/edit'
  get 'comments/update'
  get 'comments/create'
  get 'comments/destroy'
  get 'books/index'
  get 'books/new'
  get 'books/show'
  get 'books/edit'
  get 'books/update'
  get 'books/create'
  get 'books/destroy'
  get 'genres/index'
  get 'genres/new'
  get 'genres/show'
  get 'genres/edit'
  get 'genres/update'
  get 'genres/create'
  get 'genres/destroy'
  get 'users/index'
  get 'users/new'
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  get 'users/create'
  get 'users/destroy'
  root to: 'pages#home'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end
